# Auto-generated by dataset_cmds.py

DSETROOT="carla_4d/"
PORT=6132

for REDO_IDX in {1..5}
do
echo $REDO_IDX


SPLIT="train"
NAME="train_0003"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 3 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0011"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 11 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0019"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 19 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0027"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 4 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0035"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 12 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0043"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 20 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0051"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 5 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0059"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 13 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0067"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 21 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0075"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 6 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0083"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 14 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0091"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 6 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0099"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 7 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0107"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 15 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0115"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 0 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0123"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 8 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0131"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 16 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0139"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 1 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0147"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 9 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0155"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 17 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0163"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 2 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0171"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 10 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0179"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 18 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0187"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 3 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0195"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 11 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0203"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 19 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0211"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 4 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0219"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 12 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0227"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 20 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0235"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 5 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0243"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 13 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0251"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 21 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0259"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 6 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0267"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 14 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0275"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 6 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0283"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 7 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0291"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 15 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0299"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 0 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0307"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 8 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0315"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 16 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0323"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 1 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0331"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 9 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0339"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 17 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0347"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 2 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0355"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 10 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0363"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 18 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0371"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 3 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0379"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 11 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0387"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 19 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="train"
NAME="train_0395"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 4 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="val"
NAME="val_0403"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 12 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="val"
NAME="val_0411"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 20 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="val"
NAME="val_0419"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 5 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="val"
NAME="val_0427"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 13 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="val"
NAME="val_0435"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 21 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="val"
NAME="val_0443"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 6 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="val"
NAME="val_0451"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 14 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="val"
NAME="val_0459"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 6 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="val"
NAME="val_0467"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 7 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="val"
NAME="val_0475"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 15 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="val"
NAME="val_0483"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 0 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="val"
NAME="val_0491"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 8 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


SPLIT="val"
NAME="val_0499"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town04 --num_vehicles 186 --num_walkers 241 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 16 --multiview 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000 --multiview 5


done

