# Auto-generated by dataset_cmds.py

DSETROOT="carla_4d/"
PORT=6152

for REDO_IDX in {1..5}
do
echo $REDO_IDX


SPLIT="train"
NAME="train_0005"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0013"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 13 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0021"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 21 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0029"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 6 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0037"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 14 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0045"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 6 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0053"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 7 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0061"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 15 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0069"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 0 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0077"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 8 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0085"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 16 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0093"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 1 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0101"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 9 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0109"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 17 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0117"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 2 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0125"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 10 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0133"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 18 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0141"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 3 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0149"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 11 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0157"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 19 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0165"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 4 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0173"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 12 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0181"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 20 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0189"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0197"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 13 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0205"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 21 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0213"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 6 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0221"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 14 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0229"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 6 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0237"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 7 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0245"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 15 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0253"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 0 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0261"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 8 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0269"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 16 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0277"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 1 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0285"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 9 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0293"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 17 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0301"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 2 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0309"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 10 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0317"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 18 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0325"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 3 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0333"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 11 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0341"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 19 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0349"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 4 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0357"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 12 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0365"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 20 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0373"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 5 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0381"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 13 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0389"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 21 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="train"
NAME="train_0397"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 6 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="val"
NAME="val_0405"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 14 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="val"
NAME="val_0413"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 6 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="val"
NAME="val_0421"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 7 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="val"
NAME="val_0429"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 15 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="val"
NAME="val_0437"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 0 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="val"
NAME="val_0445"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 8 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="val"
NAME="val_0453"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 16 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="val"
NAME="val_0461"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 1 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="val"
NAME="val_0469"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 9 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="val"
NAME="val_0477"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 17 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="val"
NAME="val_0485"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 2 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


SPLIT="val"
NAME="val_0493"
python record_simulation.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --world Town06 --num_vehicles 218 --num_walkers 283 --safe 1 --num_frames 1000 --fps 10
python capture_sensor_data.py --record_path $DSETROOT/$SPLIT/$NAME/$NAME.log --port $PORT --weather_preset 10 --num_frames 1000 --fps 10 --time_factor 1.0
python video_scene.py --capture_path $DSETROOT/$SPLIT/$NAME --num_frames 1000


done

